version: 2
updates:
  - package-ecosystem: nuget
    directory: /HyperionScreenCap
    schedule:
      interval: weekly
    commit-message:
      prefix: chore(deps)
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore(deps)
